# Generated by Django 5.2.6 on 2025-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf_url',
            field=models.URLField(max_length=4096),
        ),
    ]
