version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: zapsign-db
    environment:
      POSTGRES_USER: zapsign
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zapsign
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zapsign -d zapsign"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: {}


