# Generated by Django 5.2.6 on 2025-09-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
