# Generated by Django 5.2.6 on 2025-09-18 16:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_email_company_password_hash'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='idx_company_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_company_email_ci'),
        ),
    ]
