from typing import Protocol, Optional
from .dtos import DocumentDTO, ZapSignCreateResult


class DocumentRepository(Protocol):
    def create(self, company_id: int, name: str, pdf_url: str) -> DocumentDTO: ...
    def get_by_id(self, document_id: int) -> Optional[DocumentDTO]: ...
    def list_all(self) -> list[DocumentDTO]: ...
    def update_partial(self, document_id: int, **fields) -> Optional[DocumentDTO]: ...
    def delete(self, document_id: int) -> bool: ...


class ZapSignClient(Protocol):
    def create(self, api_token: str, name: str, pdf_url: str) -> ZapSignCreateResult: ...

