from typing import Protocol, Optional
from .dtos import SignerDTO


class SignerCommandRepository(Protocol):
    def create(self, document_id: int, name: str, email: str) -> SignerDTO: ...
    def delete(self, signer_id: int) -> bool: ...


class SignerQueryRepository(Protocol):
    def count_by_document(self, document_id: int) -> int: ...
    def get_by_document_and_email(self, document_id: int, email: str) -> Optional[SignerDTO]: ...
    def list_by_document(self, document_id: int) -> list[SignerDTO]: ...


