from typing import Protocol, Optional
from .dtos import CompanyDTO


class CompanyRepository(Protocol):
    def create(self, name: str, api_token: str) -> CompanyDTO: ...
    def get_by_id(self, company_id: int) -> Optional[CompanyDTO]: ...
    def list_all(self) -> list[CompanyDTO]: ...
    def update_partial(self, company_id: int, **fields) -> Optional[CompanyDTO]: ...
    def delete(self, company_id: int) -> bool: ...


