# Generated by Django 5.2.6 on 2025-09-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='insights',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='missing_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='model_info',
            field=models.JSONField(default=dict),
        ),
    ]
